name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        profile: minimal

    - name: Install trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: 'latest'

    - name: SSR
      run: ./generate_static.sh

    - name: Build project
      run: trunk build --release --public-url ram-webgui

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist

